### PR TITLE
US4.3: Add Comprehensive Test Suite for All Followers Endpoints

### LINKED ISSUE #58: US4.3-Test6: Write unit tests for the followers retrieval API
Write all unit tests possible to cover all the success and error cases so that we can assure that everything works well.

### PR DESCRIPTION
**Pull request by malikmati90**
This PR introduces a full suite of tests for all the followers-related endpoints in the application, ensuring robust functionality and error handling. Each endpoint has been thoroughly tested for edge cases, success scenarios, and potential errors.  

### **Endpoints Covered:**  
1. **Follow User (`POST /followers/follow/{followee_id}`)**  
   - Tests successful follow operations.  
   - Ensures proper handling of self-follow attempts.  
   - Validates errors when following nonexistent users.  

2. **Unfollow User (`POST /followers/unfollow/{followee_id}`)**  
   - Verifies successful unfollow functionality.  
   - Handles errors for nonexistent users and self-unfollow attempts.  
   - Ensures proper behavior when unfollowing users without an existing relationship.  

3. **Get Followers (`GET /followers/get_followers/{user_id}`)**  
   - Retrieves the list of followers for a given user.  
   - Handles scenarios where the user does not exist or has no followers.  

4. **Get Followees (`GET /followers/get_followings/{user_id}`)**  
   - Retrieves the list of users a given user is following.  
   - Tests for users with no followees or nonexistent users.  

5. **Get Mutual Followers (`GET /followers/mutual-followers/{user_id_1}/{user_id_2}`)**  
   - Retrieves mutual followers between two users.  
   - Handles cases where one or both users do not exist.  
   - Validates behavior when there are no mutual followers.  

6. **Get Most Followed Users (`GET /followers/most-followed?limit={limit}`)**  
   - Fetches the list of users with the highest number of followers.  
   - Validates behavior when there are no users in the system.  
   - Tests the impact of the `limit` parameter.  

### **Test Coverage Highlights:**  
- **Success Scenarios:**  
  Ensures endpoints perform correctly under normal conditions.  

- **Error Handling:**  
  Validates appropriate error responses for scenarios such as:  
  - Nonexistent users.  
  - Invalid operations (e.g., self-follow or self-unfollow).  
  - Unauthorized access.  

- **Edge Cases:**  
  - Users with no followers or followees.  
  - Database errors during operations.  
  - Parameter-based variations (e.g., limits).  

- **Authentication Checks:**  
  Confirms endpoints require valid authentication where applicable.  

### **Testing Approach:**  
- Leveraged `pytest` with fixtures to set up mock data for realistic testing scenarios.  
- Included helper functions for reusable components like login and token generation.  
- Simulated database errors using `monkeypatch` to ensure graceful handling of unexpected issues.  

### **Additional Notes:**  
- Improved test readability and maintainability through clear structure and comments.  
- Verified tests across multiple edge cases to ensure high reliability.  
- These tests provide a solid foundation for detecting regressions in followers-related functionality.  

closes #58

### CODE REVIEW

**Review by AlejandroDS1 — CHANGES_REQUESTED** [review]
Tests do not pass

**Review by malikmati90 — COMMENTED** [review]
All tests pass now

**Comment by malikmati90** [comment]
All tests pass now correctly

**Review by AlejandroDS1 — CHANGES_REQUESTED** [review]
Tienes que hacer un update ya que han habido cambios en la rama original (se ha mergeado la PR #84). Mira que se mergeen bien los cambios. Añade, porfavor, un ultimo test al nuevo endpoint (ultimo de todos),

**Comment by malikmati90** [comment]
Ya lo he actualizado y añadido nuevos tests para el último endpoint

**Review by AlejandroDS1 — APPROVED** [review]
LGTM

**Pull request merged**
